#!/bin/bash -l
# vscode-remote-job-sge.sh
# Runs on an SGE compute node. Loads requested Lmod modules, captures the full
# resulting environment to a per-job sh-sourceable file, wires it into the VS Code
# server via ~/.vscode-server/server-env-setup, then launches sshd.
# Args: $1 = PORT, $2 = comma-separated Lmod modules (may be empty)

PORT="$1"
MODULES="$2"
VRH_DIR="$HOME/.vscode-remote-hpc"

vrh_short_host () {
    ( hostname -s 2>/dev/null ) || ( hostname 2>/dev/null | cut -d. -f1 ) || echo unknown
}

ensure_module_cmd () {
    if ! type module >/dev/null 2>&1; then
        for init in \
            "${LMOD_PKG:+$LMOD_PKG/init/bash}" \
            "${MODULESHOME:+$MODULESHOME/init/bash}" \
            /etc/profile.d/modules.sh /etc/profile.d/lmod.sh \
            /usr/share/lmod/lmod/init/bash ; do
            [ -n "$init" ] && [ -r "$init" ] && . "$init" && break
        done
    fi
    type module >/dev/null 2>&1
}

load_modules () {
    [ -z "$MODULES" ] && return 0
    if ! ensure_module_cmd; then
        >&2 echo "vscode-remote-hpc: 'module' command unavailable; skipping module load"
        return 0
    fi
    local IFS=',' m
    for m in $MODULES; do
        m="${m#"${m%%[![:space:]]*}"}"; m="${m%"${m##*[![:space:]]}"}"
        [ -z "$m" ] && continue
        if module load "$m" 2>/dev/null; then
            >&2 echo "vscode-remote-hpc: loaded module $m"
        else
            >&2 echo "vscode-remote-hpc: WARNING could not load module $m (continuing)"
        fi
    done
    return 0
}

write_env_file () {
    # $1 = destination. Build sh-sourceable export lines from env -0 (NUL-delimited
    # so values with newlines survive). Single-quote escape so /bin/sh treats values
    # literally. Skip non-identifier names (kills BASH_FUNC_x%%) and a blocklist.
    local dest="$1" tmp="${1}.tmp.$$" name val esc
    {
        while IFS= read -r -d '' kv; do
            name=${kv%%=*}; val=${kv#*=}
            case $name in
                '' ) continue ;;
                [!A-Za-z_]* ) continue ;;
                *[!A-Za-z0-9_]* ) continue ;;
            esac
            case $name in
                _|PWD|OLDPWD|SHLVL|TERM|HOSTNAME|HOST|HOSTTYPE|MACHTYPE \
                |SSH_CLIENT|SSH_CONNECTION|SSH_TTY|SSH_AUTH_SOCK|SSH_AGENT_PID \
                |LINES|COLUMNS|DISPLAY|XAUTHORITY|TMUX|STY \
                |LD_PRELOAD|BASH_ENV|ENV|PROMPT_COMMAND|PS1|PS2|PS3|PS4 \
                |LOGNAME|USER|MAIL ) continue ;;
            esac
            esc=$(printf '%s' "$val" | sed "s/'/'\\\\''/g")
            printf "export %s='%s'\n" "$name" "$esc"
        done < <(env -0)
    } > "$tmp" 2>/dev/null || { rm -f "$tmp"; return 1; }
    if sh -n "$tmp" 2>/dev/null; then            # bulletproof: only publish valid sh
        chmod 600 "$tmp" 2>/dev/null
        mv -f "$tmp" "$dest" && return 0
    fi
    >&2 echo "vscode-remote-hpc: env file failed validation; not publishing"
    rm -f "$tmp"; return 1
}

write_forcecommand_wrapper () {
    # $1 = destination. This script is run by sshd as the ForceCommand for every
    # session. It sources the job env file, then runs the client's command (how
    # VS Code launches its server -> the server inherits the job env, and the
    # terminals it spawns inherit it in turn) or a login shell for plain ssh.
    # Modern VS Code uses a CLI-launched server with no shell hook (no
    # server-env-setup), so injecting at the sshd session is the reliable place.
    local dest="$1" tmp="${1}.tmp.$$"
    cat > "$tmp" <<'WRAP'
#!/bin/bash
# Auto-generated by vscode-remote-hpc. Do not edit.
__ef="$1"
if [ -z "$__ef" ] || [ ! -r "$__ef" ]; then __ef="${VSCODE_REMOTE_HPC_ENV:-}"; fi
if [ -z "$__ef" ] || [ ! -r "$__ef" ]; then
    __h=$( (hostname -s 2>/dev/null) || (hostname 2>/dev/null | cut -d. -f1) || echo unknown )
    __ef=$(ls -1t "$HOME/.vscode-remote-hpc/env-${__h}-"*.sh 2>/dev/null | head -1)
fi
[ -n "$__ef" ] && [ -r "$__ef" ] && . "$__ef" 2>/dev/null
unset __ef __h
if [ -n "${SSH_ORIGINAL_COMMAND:-}" ]; then
    exec /bin/bash -c "$SSH_ORIGINAL_COMMAND"
else
    exec /bin/bash -l
fi
WRAP
    chmod 700 "$tmp" 2>/dev/null
    mv -f "$tmp" "$dest"
}

# ---- main ----
mkdir -p "$HOME/.ssh" 2>/dev/null
if [ ! -f "$HOME/.ssh/vscode-remote-hostkey" ]; then
    ssh-keygen -t ed25519 -f "$HOME/.ssh/vscode-remote-hostkey" -N ""
fi

mkdir -p "$VRH_DIR" 2>/dev/null
find "$VRH_DIR" -maxdepth 1 -name 'env-*.sh' -mtime +7 -delete 2>/dev/null

load_modules

ENV_FILE="$VRH_DIR/env-$(vrh_short_host)-${JOB_ID:-$$}.sh"
WRAPPER="$VRH_DIR/forcecommand.sh"
write_env_file "$ENV_FILE"        || >&2 echo "vscode-remote-hpc: continuing without env file"
write_forcecommand_wrapper "$WRAPPER" || >&2 echo "vscode-remote-hpc: could not write ForceCommand wrapper"

trap 'rm -f "$ENV_FILE"' EXIT INT TERM   # clean up this job's env file on exit

if [ -f "/usr/sbin/sshd" ]; then sshd_cmd=/usr/sbin/sshd; else sshd_cmd=sshd; fi

# ForceCommand injects the job environment into every session, so the VS Code
# server (and the terminals/tasks it spawns) inherit the SGE vars and loaded
# modules. The env file path is passed as the wrapper's first argument.
"$sshd_cmd" -D -p "$PORT" -f /dev/null \
    -o "ForceCommand=$WRAPPER $ENV_FILE" \
    -h "$HOME/.ssh/vscode-remote-hostkey"
